/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
package view;
import controller.*;
import model.*;

public class AddAccount extends javax.swing.JDialog {
    private BankAccountController bank_account_controller;
    private BankAccount[] accounts;
    private User user;


    /**
     * Creates new form Add_account
     */
    public AddAccount(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        this.user = user;
        this.bank_account_controller = new BankAccountController();
        initComponents();
        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frist_name_label = new javax.swing.JLabel();
        first_name_textfield = new javax.swing.JTextField();
        last_name_label = new javax.swing.JLabel();
        last_name_textfield = new javax.swing.JTextField();
        SSN_label = new javax.swing.JLabel();
        ssn_textfield = new javax.swing.JTextField();
        Acc_type_label = new javax.swing.JLabel();
        account_type_box = new javax.swing.JComboBox<>();
        Initial_deposit_label = new javax.swing.JLabel();
        initial_deposit_textfield = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 2, 2));

        frist_name_label.setText("First Name");
        getContentPane().add(frist_name_label);

        first_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(first_name_textfield);

        last_name_label.setText("Last Name");
        getContentPane().add(last_name_label);

        last_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(last_name_textfield);

        SSN_label.setText("Social Security Number");
        getContentPane().add(SSN_label);
        getContentPane().add(ssn_textfield);

        Acc_type_label.setText("Account Type");
        getContentPane().add(Acc_type_label);

        account_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Checking", "Securtiy"}));
        account_type_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_type_boxActionPerformed(evt);
            }
        });
        account_type_box.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                account_type_boxPropertyChange(evt);
            }
        });
        getContentPane().add(account_type_box);

        Initial_deposit_label.setText("Initial Deposit");
        getContentPane().add(Initial_deposit_label);

        initial_deposit_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initial_deposit_textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(initial_deposit_textfield);

        submit_button.setText("SUBMIT");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(submit_button);

        cancel_button.setText("CANCEL");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void first_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_textfieldActionPerformed

    private void last_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_textfieldActionPerformed

    private void account_type_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_type_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account_type_boxActionPerformed

    private void initial_deposit_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initial_deposit_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initial_deposit_textfieldActionPerformed

    private void account_type_boxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_account_type_boxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_account_type_boxPropertyChange

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
         String first = "";
         String last = "";
         String ssn = "";
         Double amount ;
         StringBuilder errors = new StringBuilder();
        //first name should not be empty
        
        if (first_name_textfield.getText().isBlank()){
            errors.append("First name cannot be empty\n");
        }   
        else{
            first = first_name_textfield.getText();
        }

        //last name should not be empty
        
        if (last_name_textfield.getText().isBlank()){
            errors.append("Last name cannot be empty\n");
        }  
        else{
            last = last_name_textfield.getText();
        }
        
        // SSN should not be empty and should be a number
        if (ssn_textfield.getText().isBlank()){
            errors.append("SSN cannot be empty\n");
        } 
        
        if (!ssn_textfield.getText().matches("(\\d{3}-?){2}\\d{4}")){
            errors.append("SSN should be a number with format xxx-xx-xxxx\n");
        }
        else{
            ssn = ssn_textfield.getText().replace("-","");
        }
        
        // intial deposit should not be empty

        if (initial_deposit_textfield.getText().isBlank()){
            errors.append("Intial deposit should not be empty.\n");

        }
        else{
            try{
                amount = Double.parseDouble(initial_deposit_textfield.getText());
            }
            catch(NumberFormatException ex){
                errors.append("Intial deposit must be a number.\n");
            }
        }
        
        if (errors.length()>0){
            javax.swing.JOptionPane.showMessageDialog(this,errors,"Error",javax.swing.JOptionPane.WARNING_MESSAGE);

        }
        else{
            if (account_type_box.getSelectedItem().toString() == "savings"){
                // Call the account creation controller
                bank_account_controller.openAccount(this.user.getUsername(),"savings");
                
            }
             if (account_type_box.getSelectedItem().toString() == "checking"){
                // Call the account creation controller
                bank_account_controller.openAccount(this.user.getUsername(),"checking");

            }
             if (account_type_box.getSelectedItem().toString() == "security"){
                // Call the account creation controller
                bank_account_controller.openAccount(this.user.getUsername(),"checking");

             }
             
            this.accounts = bank_account_controller.getAllBankAccounts(this.user.getUsername());
            this.dispose();

        }
        
        
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed
    
    
    /**
     *
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Add_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Add_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Add_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Add_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Add_account dialog = new Add_account(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    public BankAccount[] get_bank_accounts(){
        return this.accounts;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Acc_type_label;
    private javax.swing.JLabel Initial_deposit_label;
    private javax.swing.JLabel SSN_label;
    private javax.swing.JComboBox<String> account_type_box;
    private javax.swing.JButton cancel_button;
    private javax.swing.JTextField first_name_textfield;
    private javax.swing.JLabel frist_name_label;
    private javax.swing.JTextField initial_deposit_textfield;
    private javax.swing.JLabel last_name_label;
    private javax.swing.JTextField last_name_textfield;
    private javax.swing.JTextField ssn_textfield;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
