


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
package view;
import controller.*;
import model.*;
import java.awt.Color;

public class DepositMoneyFrame extends javax.swing.JDialog {

    /**
     * Creates new form deposit_money_frame
     */
    private BankAccount user_bank_account;
    private BankAccountController bank_account_controller;

    public DepositMoneyFrame(java.awt.Frame parent, boolean modal, BankAccount acc) {
        
     
        super(parent, modal);
        this.user_bank_account = acc;
        this.bank_account_controller = new BankAccountController();
        initComponents();
        this.getContentPane().setBackground(Color.GREEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Currency_type_label = new javax.swing.JLabel();
        Currency_type_combox = new javax.swing.JComboBox<>();
        Deposit_amount_label = new javax.swing.JLabel();
        deposit_amount_text = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        Currency_type_label.setText("Currency Type");
        getContentPane().add(Currency_type_label);

        Currency_type_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "CNY"}));
        getContentPane().add(Currency_type_combox);

        Deposit_amount_label.setText("Deposit Amount");
        getContentPane().add(Deposit_amount_label);
        getContentPane().add(deposit_amount_text);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(submit_button);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        
        String currency_type = Currency_type_combox.getSelectedItem().toString();
        double amt = Double.parseDouble(deposit_amount_text.getText());
        BaseCurrency currency = new BaseCurrency(currency_type,amt);
        if(bank_account_controller.deposit(this.user_bank_account,currency).status){
           javax.swing.JOptionPane.showMessageDialog(this,"Deposit succesfull","Deposit message",javax.swing.JOptionPane.PLAIN_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"Deposit unsuccesfull","Deposit message",javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(deposit_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(deposit_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(deposit_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(deposit_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                deposit_money_frame dialog = new deposit_money_frame(new javax.swing.JFrame(), true,this.user_bank_account);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Currency_type_combox;
    private javax.swing.JLabel Currency_type_label;
    private javax.swing.JLabel Deposit_amount_label;
    private javax.swing.JButton cancel_button;
    private javax.swing.JTextField deposit_amount_text;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
