package view;
import controller.*;
import model.*;
import javax.swing.*;
import java.awt.event.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
public class LoanForm extends javax.swing.JDialog {

    /**
     * Creates new form LoanForm
     */
    private Checking user_bank_account;
    private LoanController loan_controller;
    public LoanForm(java.awt.Frame parent, boolean modal,BankAccount acc) {
        super(parent, modal);
        this.loan_controller = new LoanController();
        this.user_bank_account = (Checking) acc;
        initComponents();
        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currency_type_box = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        amount_field = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("CurrencyType");
        jPanel1.add(jLabel1);

        currency_type_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD",
                "EUR",
                "JPY",
                "GBP",
                "AUD",
                "CAD",
                "CNY",
                "HKD"  }));
        jPanel1.add(currency_type_box);

        jLabel2.setText("Amount");
        jPanel1.add(jLabel2);
        jPanel1.add(amount_field);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(submit_button);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_button);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String crr_type = currency_type_box.getSelectedItem().toString();
        Double amt = Double.parseDouble(amount_field.getText());

        BaseCurrency currency = new BaseCurrency(crr_type,amt);
        OpResponse res = this.loan_controller.applyLoan(this.user_bank_account,currency);

        if(res.status){
            javax.swing.JOptionPane.showMessageDialog(this, res.response, "Message",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, res.response, "Message",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JTextField amount_field;
    private javax.swing.JButton cancel_button;
    private javax.swing.JComboBox<String> currency_type_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit_button;
    // End of variables declaration
}

