package view;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author oshorawal
 */

public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form Manager_frame
     */
    public ManagerFrame() {
        initComponents();
         this.getContentPane().setBackground(Color.GREEN);
         manager_panel.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manager_panel = new javax.swing.JPanel();
        view_report = new javax.swing.JButton();
        manage_stocks = new javax.swing.JButton();
        View_customer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        view_report.setText("View Report");
        view_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_reportActionPerformed(evt);
            }
        });

        manage_stocks.setText("Manage Stocks");
        manage_stocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_stocksActionPerformed(evt);
            }
        });

        View_customer.setText("View Customer");
        View_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_customerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manager_panelLayout = new javax.swing.GroupLayout(manager_panel);
        manager_panel.setLayout(manager_panelLayout);
        manager_panelLayout.setHorizontalGroup(
            manager_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manager_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(view_report)
                .addGap(18, 18, 18)
                .addComponent(manage_stocks)
                .addGap(18, 18, 18)
                .addComponent(View_customer)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        manager_panelLayout.setVerticalGroup(
            manager_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manager_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(manager_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_report)
                    .addComponent(manage_stocks)
                    .addComponent(View_customer))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manager_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manager_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manage_stocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_stocksActionPerformed
        // TODO add your handling code here:
        StocksFrame stocks = new StocksFrame();
        stocks.setVisible(true);
    }//GEN-LAST:event_manage_stocksActionPerformed

    private void view_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_reportActionPerformed
        // TODO add your handling code here:
        
        // Controller for viewing the todays transaction.
    }//GEN-LAST:event_view_reportActionPerformed

    private void View_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_customerActionPerformed
        // TODO add your handling code here:
        
        //Controller to view all the user of the bank
    }//GEN-LAST:event_View_customerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View_customer;
    private javax.swing.JButton manage_stocks;
    private javax.swing.JPanel manager_panel;
    private javax.swing.JButton view_report;
    // End of variables declaration//GEN-END:variables
}
