package view;
import controller.*;
import model.*;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
public class ReviewLoan extends javax.swing.JDialog {

    /**
     * Creates new form ReviewLoan
     */
    private LoanController loan_controller;
    public ReviewLoan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.loan_controller = new LoanController();
        initComponents();
        this.setLocationRelativeTo(parent);
//        this.setcolor
        clear_table();
        addDataToTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Approve_loan_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loan_table = new javax.swing.JTable();
        reject_loan_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Approve_loan_button.setText("Approve Loan");
        Approve_loan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Approve_loan_buttonActionPerformed(evt);
            }
        });

        loan_table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                },
                new String [] {
                        "ID", "status", "Account Number", "CurrencyType","Amount","Date","Interest Rate"
                }
        ));
        loan_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(loan_table);

        reject_loan_button.setText("Reject Loan");
        reject_loan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject_loan_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(Approve_loan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(reject_loan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(27, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Approve_loan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reject_loan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void Approve_loan_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int row_selected = loan_table.getSelectedRow();
        long loanId = (long) loan_table.getValueAt(row_selected, 0);
        OpResponse res;
        if (row_selected >= 0) {
            res = this.loan_controller.reviewLoan(loanId, 1);
            javax.swing.JOptionPane.showMessageDialog(this, res.getResponse(), "Message",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"No row selected in table", "Message",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        clear_table();
        addDataToTable();
    }

    private void reject_loan_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int row_selected = loan_table.getSelectedRow();
        long loanId = (long) loan_table.getValueAt(row_selected, 0);
        OpResponse res;
        if (row_selected >= 0) {
            res = this.loan_controller.reviewLoan(loanId, 0);
            javax.swing.JOptionPane.showMessageDialog(this, res.getResponse(), "Message",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,"No row selected in table", "Message",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        clear_table();
        addDataToTable();
    }

    private void clear_table(){
        DefaultTableModel table = (DefaultTableModel)  loan_table.getModel();
        for (int i = table.getRowCount() - 1; i >= 0; i--) {
            table.removeRow(i);
        }
    }

    private void addDataToTable(){
        DefaultTableModel table = (DefaultTableModel)  loan_table.getModel();
        OpResponse res = this.loan_controller.getAllLoans();
        List<Loan> loans = (ArrayList<Loan>) res.data;
        for(Loan loan : loans){
            table.addRow(new Object[]{loan.getId(),loan.getStatus(),loan.getAccount().getAccountNumber(),loan.getCurrency().getName(),loan.getCurrency().getAmount(),loan.getDate(),loan.getInterestRate()});
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReviewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReviewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReviewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReviewLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ReviewLoan dialog = new ReviewLoan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify
    private javax.swing.JButton Approve_loan_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loan_table;
    private javax.swing.JButton reject_loan_button;
    // End of variables declaration
}

