/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
package view;
import controller.*;

public class SignUp extends javax.swing.JDialog {

    /**
     * Creates new form Sign_up
     */
    private LoginController login_controller;
    
    public SignUp(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        this.login_controller = new LoginController();
        initComponents();
        setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        address_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        birthday_text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        getContentPane().add(name_text);

        jLabel2.setText("Address");
        getContentPane().add(jLabel2);
        getContentPane().add(address_Text);

        jLabel3.setText("Birthday");
        getContentPane().add(jLabel3);
        getContentPane().add(birthday_text);

        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        getContentPane().add(username_text);

        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        getContentPane().add(password_text);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(submit_button);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
         String name = "";
         String address = "";
         String birthday = "";
         String username = "";
         String password = "";
         StringBuilder errors = new StringBuilder();
         
         if (name_text.getText().isBlank()){
            errors.append("Name cannot be empty\n");
        }   
        else{
            name = name_text.getText();
        }

        
        if (address_Text.getText().isBlank()){
            errors.append("Address cannot be empty\n");
        }  
        else{
            address = address_Text.getText();
        }
        
        if (birthday_text.getText().isBlank()){
            errors.append("Birth date cannot be empty\n");
        }  
        else{
            birthday = birthday_text.getText();
        }
        
        
        if (username_text.getText().isBlank()){
            errors.append("Username cannot be empty\n");
        }  
        else{
            username = username_text.getText();
        }
        
                
        if (password_text.getPassword().toString().isBlank()){
            errors.append("Password cannot be empty\n");
        }  
        else{
            password = password_text.getPassword().toString();
        } 
        
        if (errors.length()>0){
            javax.swing.JOptionPane.showMessageDialog(this,errors,"Error",javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        else{
            if(this.login_controller.signUp(name,address,birthday,username,password)){
               javax.swing.JOptionPane.showMessageDialog(this,"Sign Up successfull","Message",javax.swing.JOptionPane.PLAIN_MESSAGE);
            }
            else{
               javax.swing.JOptionPane.showMessageDialog(this,"Sign Up unsuccessfull","Message",javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }

    //GEN-LAST:event_submit_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Sign_up dialog = new Sign_up(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_Text;
    private javax.swing.JTextField birthday_text;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name_text;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables
}
