/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author oshorawal
 */
package view;
import controller.*;
import model.*;
public class TransferMoneyFrame extends javax.swing.JDialog {

    /**
     * Creates new form transfer_money_frame
     */
    private BankAccount user_bank_account;
    private BankAccountController bank_account_controller;
    public TransferMoneyFrame(java.awt.Frame parent, boolean modal, BankAccount acc) {
        super(parent, modal);
        this.user_bank_account = acc;
        this.bank_account_controller = new BankAccountController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account_number_button = new javax.swing.JLabel();
        account_number_text = new javax.swing.JTextField();
//        currency_type_button = new javax.swing.JLabel();
//        currency_type_jbox = new javax.swing.JComboBox<>();
        amount_button = new javax.swing.JLabel();
        amount_text_field = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        account_number_button.setText("Account Number");
        getContentPane().add(account_number_button);
        getContentPane().add(account_number_text);

//        currency_type_button.setText("Currency Type");
//        getContentPane().add(currency_type_button);

//        currency_type_jbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "INR", "CNY"}));
//        getContentPane().add(currency_type_jbox);

        amount_button.setText("Amount");
        getContentPane().add(amount_button);
        getContentPane().add(amount_text_field);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(submit_button);

        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        String account_number = account_number_text.getText();
        BankAccount account_to_transfer = (BankAccount) bank_account_controller.getAccountByNumber(account_number).data;
        String currency_type = "USD";
        double amount = Double.parseDouble(amount_text_field.getText());
        BaseCurrency crr = new BaseCurrency(currency_type,amount);
        OpResponse res;
        res = bank_account_controller.transfer(this.user_bank_account,account_to_transfer,crr);
        
        if (res.status){
            javax.swing.JOptionPane.showMessageDialog(this,res.response,"Message",javax.swing.JOptionPane.PLAIN_MESSAGE);
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this,res.response,"Message",javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(transfer_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(transfer_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(transfer_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(transfer_money_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                transfer_money_frame dialog = new transfer_money_frame(new javax.swing.JFrame(), true,this.user_bank_account);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_number_button;
    private javax.swing.JTextField account_number_text;
    private javax.swing.JLabel amount_button;
    private javax.swing.JTextField amount_text_field;
    private javax.swing.JButton cancel_button;
//    private javax.swing.JLabel currency_type_button;
//    private javax.swing.JComboBox<String> currency_type_jbox;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
